### ISSUE TITLE
Welcome to my repo!

### ISSUE THREAD

**Issue by Tset-Noitamotua** [Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration#1]
Please feal free to ask, comment, contribute or just share your ideas!

Tset Noitamotua

**Comment by RaiMan** [comment]
Again congratulations.
small typo in the new headline: greate tuturial -> great tutorial

**Comment by Tset-Noitamotua** [comment]
oh yes, thanks!

**Comment by RaiMan** [comment]
not for that ;-)
