### ISSUE TITLE
step_2 robottest.bat [ ERROR ] Expected at least 1 argument, got 0.

### ISSUE THREAD

**Issue by aedahh** [Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration#12]
Hello, 
When I run robottest.bat I am getting error:
[ ERROR ] Expected at least 1 argument, got 0.

What argument is it expecting? 

I am using sikulix.jar from sikulixsetup-1.1.0, robotframework-2.8.7.jar.
Thanks

**Comment by RaiMan** [comment]
Do you have more details or a guess about the place in the scripts, where that happened?
Step_2 or Step_3 ?

**Comment by Tset-Noitamotua** [comment]
Quick guess (not 100% sure) it is expecting a robot file (`.robot` or `.txt`)

Try something like `robottest.bat you_test_case.robot`

**Comment by aedahh** [comment]
Thank you all for the responses, now I can run test2 successfully.
by executing command below
robottest.bat robot_suite\verify_operations.txt
