### ISSUE TITLE
importing Sikuli stuff

### ISSUE THREAD

**Issue by Tset-Noitamotua** [Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration#2]
For calc.py in step_1 would it be sufficient and ok to import this?

``` python
from sikuli import JEnv
from sikuli import Env
from sikuli import setBundlePath
from sikuli.Sikuli import App
from sikuli import Region
from sikuli import Screen
from sikuli import KEY_CTRL
```

Instead of doing this:

``` python
from sikuli import *
```

**Comment by RaiMan** [comment]
No, please do not do that.

The wrapper sikuli.Sikuli.py is there to separate the Jython from the Java level and assures, that works, what is mentioned in the docs. It leaves the freedom to me, to change what I think is needed under the hood and still having a layer, that keeps things compatible.

Of course, you are free, to do what you want, but in case of problems, I will insist on using 
from sikuli import *

and ask you to reproduce the problem.

**Comment by Tset-Noitamotua** [comment]
Ok. I will consider it in the future.
