### ISSUE TITLE
Buildin Jython interpreter in sikulix.jar? (runsikulix.cmd)

### ISSUE THREAD

**Issue by Tset-Noitamotua** [Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration#3]
Does sikulix.jar has a own Jython interpreter build in? Thus when using `runsikulix.cmd -r calc.sikuli` or `java -jar "~yourpath_to~\sikulix.jar" -r calc.sikuli` the buildin interpreter is used instead the one intalled on my system?

**Comment by RaiMan** [comment]
yes, it has the 2.7b3 bundled.

This is the reason, why one should not use it with RobotFramework or other usages, where one does not use the SikuliX IDE (currently not possible to fix the python path / sys.path on the fly for that).

With everything, that is not pure Jython scripting one has to use sikulixapi.jar.
