### ISSUE TITLE
NullPointerException when using addImagePath

### ISSUE THREAD

**Issue by Tset-Noitamotua** [Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration#5]
I don't know if this is a bug or if I´m doing something wrong.

![NullPointerException_addImagePath](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/error_NullPointerException_addImagePath.png)

**Comment by RaiMan** [comment]
you either have to use double-backslashes or a path string with \ has to be noted as r"…" (in this case no trailing \ possible though)

BTW: you still have these org.sikuli.script…. imports. as mentioned already: do not do that. If you have problems with the IntelliJ's syntax error grumbling, only use qualified method calls.

**Comment by Tset-Noitamotua** [comment]
Thanx. Will try that.

About imports: screenshot is a little outdated. I don't use java level imports any more :-)

**Comment by RaiMan** [comment]
ok, I already wondered to get all the notification e-mails again.
sorry for the buzz.
