### ISSUE TITLE
Invalid BundlePath [error]

### ISSUE THREAD

**Issue by Tset-Noitamotua** [Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration#6]
Again .. I don't know ... is it me or is it SikuliX who messed things up?

![error invalid BundlePath](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/error_invalid_BundlePath.png)

**Comment by RaiMan** [comment]
known problem: there are different initialization paths depending on the usage.
will be fixed with the final version.

so for now use what works ;-)
